"""Add assigned_to into ticket.

Revision ID: 290775c91658
Revises: 0bfc54a3dce2
Create Date: 2026-01-16 18:53:12.686941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290775c91658'
down_revision = '0bfc54a3dce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
    'fk_ticket_assigned_to_user',
    'user',
    ['assigned_to'],
    ['id']
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###
