"""Added category into ticket.

Revision ID: 74f35a2dd49e
Revises: 1c8f55d1aec7
Create Date: 2026-01-14 19:22:47.852164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f35a2dd49e'
down_revision = '1c8f55d1aec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
